github:
  user: "Jenkins Infra Bot (updatecli)"
  email: "60776566+jenkins-infra-bot@users.noreply.github.com"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  owner: "jenkins-infra"
  repository: "packer-images"

jdks:
  - major: 8
  - major: 11
  - major: 17
  - major: 21
  - major: 25

windowsVersions:
  - version: 2019
    awsDescription: Microsoft Windows Server 2019 Core with EC2LaunchV2\, English locale AMI provided by Amazon
  - version: 2022
    awsDescription: Microsoft Windows Server 2022 Core Locale English AMI provided by Amazon
  - version: 2025
    awsDescription: Microsoft Windows Server 2025 Core Locale English AMI provided by Amazon
